Add Review system and cacheable translation to finnish using Redis
MotherOfRaccoons/dead-moroz pull request #4
Opened 2021-01-22 18:34 UTC by MotherOfRaccoons

2021-01-24 15:08 UTC, ARtoriouSs requested changes

2021-01-24 15:08 UTC, ARtoriouSs commented on app/controllers/assessments_controller.rb
> +    @user = User.find(params[:user_id])
You can move it to the method like you did before:

```ruby
def user
  @user ||= User.find(params[:user_id])
end
```

Do it for all cases

2021-01-24 15:08 UTC, ARtoriouSs commented on app/controllers/users_controller.rb
> +    @users = User.all
There are 2,7 billions of children in the world, so you need to add pagination here

2021-01-24 15:08 UTC, ARtoriouSs commented on app/controllers/users_controller.rb
> +      JSON.parse(response.body)['data']['translations'].first['translatedText']
Move it to the client service like `app/services/google_translate/client.rb` and call it somehow like `Client.translate`

2021-01-24 15:08 UTC, ARtoriouSs commented on app/javascript/packs/users.js
> +  });
I think it's better to separate this listeners and not chain them
```js
  $('#review-modal').on('shown.bs.modal', function() {
    $(this).find('#review-body').focus();
  });

  $('#review-modal').on('hidden.bs.modal', function() {
    $(this).find('#review-body').val('');
  });
```

Here and below

2021-01-24 15:08 UTC, ARtoriouSs commented on app/models/assessment.rb
> +  validates :value, presence: true, numericality: { greater_than: 0, less_than: 11 }
Maybe better to use  `greater_than_or_equal_to: 1` and `less_than_or_equal_to: 10` here

2021-01-24 15:08 UTC, ARtoriouSs commented on app/models/user.rb
> +
I believe these methods are generated by default by enum

2021-01-24 15:08 UTC, ARtoriouSs commented on app/views/users/index.erb
> +</table>
Not a big deal, but there is no newline at the end of the file. You can configure your editor to automatically add it

2021-01-24 15:08 UTC, ARtoriouSs commented on spec/requests/review_request_spec.rb
> +      post "/users/#{user.id}/reviews/", params: {
You can use route helpers, like `user_reviews_path(user.id)` (or something like this)
Here and in other cases

2021-01-24 15:08 UTC, ARtoriouSs commented on spec/requests/review_request_spec.rb
> +      post "/users/#{user.id}/reviews/", params: {
Also you can move params to a separate variable like
```ruby
let(:valid_params) do
  {
    review: { 
      body: attributes_for(:review)[:body]
    }
  }
end
```

2021-01-24 15:08 UTC, ARtoriouSs commented on spec/requests/image_request_spec.rb
> +    it 'fails when image is not provided' do
The example message doesn't reflect the expectation, because you expect it to redirect, but the message says that it should fail

2021-01-24 15:08 UTC, ARtoriouSs commented on spec/requests/assessment_request_spec.rb
> +      post "/users/#{user.id}/assessments/", params: {
Same, move params to `let`

2021-01-24 15:08 UTC, ARtoriouSs commented on db/migrate/20210122091357_create_assessments.rb
> +    add_foreign_key :assessments, :users, column: :target_id
If I'm not mistaken `t.belongs_to` adds the column, index, and a foreign key at the same time, so you don't need to explicitly call `add_foreign_key`

2021-01-24 15:08 UTC, ARtoriouSs commented on db/migrate/20210122091357_create_assessments.rb
> +      t.belongs_to :author, null: true
No need to use `null: true`, because it's true by default

2021-01-24 15:08 UTC, ARtoriouSs commented on db/migrate/20210122091357_create_assessments.rb
> +      t.integer :value,     null: false, limit: 1
Maybe `limit: 10`?

2021-01-24 15:08 UTC, ARtoriouSs commented on db/migrate/20210120145754_create_reviews.rb
> +end
Same comments as previous migration

2021-01-24 15:08 UTC, ARtoriouSs commented on config/locales/en.yml
>    hello: "Hello world"
I think it's unnecessary here :)

2021-01-24 15:08 UTC, ARtoriouSs commented
Also, remove the `(method` file

2021-01-24 20:05 UTC, MotherOfRaccoons commented on db/migrate/20210122091357_create_assessments.rb
> +      t.integer :value,     null: false, limit: 1
Limit for integer columns represents the number of bytes

2021-01-26 11:46 UTC, ARtoriouSs commented on db/migrate/20210122091357_create_assessments.rb
> +      t.integer :value,     null: false, limit: 1
Oh, ok

2021-01-26 12:08 UTC, ARtoriouSs requested changes

2021-01-26 12:08 UTC, ARtoriouSs commented on app/services/google_translate.rb
> +    Rails.cache.fetch(['translate', key], expires_in: 1.hour) do
It's better to make caching optional in this service:
```ruby
def translate(text, cache_key: nil)
  if cache_key.present?
    # cache things ...
  else
    # translate without caching ...
  end
end
```
And if you will not need caching you can just call it without cache key
Alternatively, you can leave caching in the controller

2021-01-26 12:08 UTC, ARtoriouSs commented on db/migrate/20210114105242_create_gifts.rb
> +      t.belongs_to :added_by,   foreign_key: { to_table: 'users' }
Oh, I understood why you added foreign keys separately, Rails cannot understand to which table create a constraint, so it was ok, sorry. Well, now it's even better :)

2021-01-26 13:52 UTC, ARtoriouSs approved these changes

2021-01-26 13:54 UTC, merged